"""empty message

Revision ID: 888b322ff8bf
Revises: 1246fa09f4f6
Create Date: 2021-01-11 17:04:19.523916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '888b322ff8bf'
down_revision = '1246fa09f4f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.Integer(), nullable=True),
    sa.Column('update_time', sa.Integer(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=True, comment='项目名'),
    sa.Column('product', sa.Integer(), nullable=False, comment='所属产品'),
    sa.ForeignKeyConstraint(['product'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    # ### end Alembic commands ###
