"""empty message

Revision ID: 8a54ffd6ce32
Revises: 4bdc54131719
Create Date: 2021-04-15 11:12:24.825059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a54ffd6ce32'
down_revision = '4bdc54131719'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bugs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('createrName', sa.String(length=32), nullable=False, comment='创建者姓名'))
        batch_op.add_column(sa.Column('updaterName', sa.String(length=32), nullable=False, comment='修改者姓名'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bugs', schema=None) as batch_op:
        batch_op.drop_column('updaterName')
        batch_op.drop_column('createrName')

    # ### end Alembic commands ###
