"""empty message

Revision ID: 93f3f273f174
Revises: e86478bd8ac9
Create Date: 2021-03-04 15:50:25.670229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93f3f273f174'
down_revision = 'e86478bd8ac9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.Integer(), nullable=True),
    sa.Column('update_time', sa.Integer(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('bug', sa.Integer(), nullable=False, comment='所属bug'),
    sa.Column('content', sa.TEXT(), nullable=True, comment='备注内容'),
    sa.Column('noteMan', sa.Integer(), nullable=False, comment='备注人'),
    sa.ForeignKeyConstraint(['bug'], ['bugs.id'], ),
    sa.ForeignKeyConstraint(['noteMan'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note')
    # ### end Alembic commands ###
