"""empty message

Revision ID: a6ae6833b93b
Revises: 4314bfb6c7fa
Create Date: 2021-02-04 16:15:24.436579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6ae6833b93b'
down_revision = '4314bfb6c7fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bug_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.Integer(), nullable=True),
    sa.Column('update_time', sa.Integer(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True, comment='bug模版'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bugs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model', sa.Integer(), nullable=True, comment='应用模版'))
        batch_op.create_foreign_key(None, 'bug_model', ['model'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bugs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('model')

    op.drop_table('bug_model')
    # ### end Alembic commands ###
