"""empty message

Revision ID: e86478bd8ac9
Revises: 
Create Date: 2021-02-05 15:59:43.208810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e86478bd8ac9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bug_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.Integer(), nullable=True),
    sa.Column('update_time', sa.Integer(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True, comment='bug模版'),
    sa.Column('content', sa.TEXT(), nullable=True, comment='模版内容'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bugs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.Integer(), nullable=True),
    sa.Column('update_time', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True, comment='BUG标题'),
    sa.Column('level', sa.Enum('p1', 'p2', 'p3', 'p4'), server_default='p3', nullable=True, comment='BUG严重等级'),
    sa.Column('priority', sa.Enum('p1', 'p2', 'p3', 'p4'), server_default='p3', nullable=True, comment='BUG优先级'),
    sa.Column('status', sa.Enum('ACTIVE', 'RESOLVED', 'CLOSED'), server_default='ACTIVE', nullable=True, comment='BUG状态'),
    sa.Column('confirmed', sa.Boolean(), nullable=True, comment='是否确认'),
    sa.Column('creater', sa.Integer(), nullable=False, comment='创建者'),
    sa.Column('updater', sa.Integer(), nullable=True, comment='修改者'),
    sa.Column('assignedTo', sa.Integer(), nullable=True, comment='指派给'),
    sa.Column('resolvedBy', sa.Integer(), nullable=True, comment='解决者'),
    sa.Column('mailTo', sa.Integer(), nullable=True, comment='抄送给'),
    sa.Column('stepsBody', sa.TEXT(), nullable=True, comment='步骤'),
    sa.Column('solution', sa.Integer(), nullable=True, comment='解决方案'),
    sa.Column('platform', sa.Integer(), nullable=True, comment='测试平台'),
    sa.Column('product', sa.Integer(), nullable=True, comment='所属项目'),
    sa.Column('build', sa.Integer(), nullable=False, comment='版本'),
    sa.Column('errorType', sa.Integer(), nullable=True, comment='错误类型'),
    sa.Column('bug_model', sa.Integer(), nullable=True, comment='应用模版'),
    sa.ForeignKeyConstraint(['assignedTo'], ['user.id'], ),
    sa.ForeignKeyConstraint(['bug_model'], ['bug_model.id'], ),
    sa.ForeignKeyConstraint(['build'], ['build.id'], ),
    sa.ForeignKeyConstraint(['creater'], ['user.id'], ),
    sa.ForeignKeyConstraint(['errorType'], ['error_type.id'], ),
    sa.ForeignKeyConstraint(['mailTo'], ['user.id'], ),
    sa.ForeignKeyConstraint(['platform'], ['platform.id'], ),
    sa.ForeignKeyConstraint(['product'], ['product.id'], ),
    sa.ForeignKeyConstraint(['resolvedBy'], ['user.id'], ),
    sa.ForeignKeyConstraint(['solution'], ['solution.id'], ),
    sa.ForeignKeyConstraint(['updater'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bugs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bugs_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bugs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bugs_title'))

    op.drop_table('bugs')
    op.drop_table('bug_model')
    # ### end Alembic commands ###
